"""
JSON to Excel Spreadsheet Generator

This script reads the output.json file generated by pdf_to_json.py,
parses the raw text into structured fields for each asset,
and creates a formatted Excel spreadsheet with one row per asset.

Dependencies:
    pip install openpyxl
"""

import json
import re
from pathlib import Path

from openpyxl import Workbook
from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.utils import get_column_letter


# ---------------------------------------------------------------------------
# Constants: define the known field labels and GN22 element names
# ---------------------------------------------------------------------------

# Fields where the value appears on the NEXT line after the label
NEXT_LINE_FIELDS = [
    "Column Name",
    "Next test",
    "Central asset Id",
    "Asset Number",
    "Column Height (m)",
    "Street",
    "Id",
    "Road Number",
    "Column type",
    "% Loss Max",
    "Ward",
    "Material",
    "Commission Date",
    "Heritage Y/N",
    "% Loss Ave (PL)",
    "OSE,OSN",
    "Listed status",
    "Thickness Ave (mm)",
    "Fixing type",
    "Condition",
    "CCIav",
    "CCIcrt",
    "ARL (years)",
    "Test date",
]

# Fields where the value is embedded on the SAME line as the label
INLINE_FIELDS = {
    "Thickness Max (mm)": r"Thickness Max \(mm\)\s+(.+)",
    "Thickness (mm) Min": r"Thickness \(mm\) Min\s+(.+)",
}

# The 9 GN22 structural element names to look for
GN22_ELEMENTS = [
    "base external",
    "base internal",
    "door",
    "embellishment",
    "foundation",
    "lantern",
    "shaft external",
    "shaft internal",
    "shoulder",
]

CRITICAL_SEVERITY_GRADES = {"C", "D", "E"}
ARL_THRESHOLD = 10

# Column order for the Excel spreadsheet
COLUMN_ORDER = [
    # Identity
    "Central asset Id",
    "Column Name",
    "Id",
    "Street",
    "Road Number",
    "Ward",
    # Characteristics
    "Column type",
    "Column Height (m)",
    "Material",
    "Fixing type",
    "Heritage Y/N",
    "Listed status",
    "Commission Date",
    "OSE,OSN",
    # Condition indices
    "Condition",
    "CCIav",
    "CCIcrt",
    "ARL (years)",
    # Thickness and loss measurements
    "Thickness Max (mm)",
    "Thickness Min (mm)",
    "Thickness Ave (mm)",
    "% Loss Max",
    "% Loss Ave (PL)",
    # Test dates
    "Test date",
    "Next test",
]


def parse_asset_text(raw_text: str) -> dict:
    """Parse the raw text from page 1 of a PDF into structured fields.

    Walks through the text line by line, matching known field labels
    and extracting their values. Handles three patterns:
    - Next-line values: label on one line, value on the next
    - Inline values: value embedded on the same line as the label
    - GN22 element blocks: element name followed by severity, extent, comment

    Args:
        raw_text: The raw text string extracted from page 1 of the PDF.

    Returns:
        A dictionary mapping field names to their extracted values.
    """

    # Split the text into individual lines for processing
    lines = raw_text.split("\n")
    parsed = {}

    # Step 1: Extract next-line fields (label on one line, value on the next)
    for i, line in enumerate(lines):
        stripped = line.strip()

        # Check if this line matches a known next-line field label
        for field in NEXT_LINE_FIELDS:
            if stripped == field and i + 1 < len(lines):
                parsed[field] = lines[i + 1].strip()
                break

    # Step 2: Extract inline fields (value on the same line as the label)
    for field, pattern in INLINE_FIELDS.items():
        for line in lines:
            match = re.search(pattern, line.strip())
            if match:
                # Rename "Thickness (mm) Min" to "Thickness Min (mm)" for consistency
                display_name = "Thickness Min (mm)" if field == "Thickness (mm) Min" else field
                parsed[display_name] = match.group(1).strip()
                break

    # Step 3: Extract GN22 element assessments (severity, extent, comment)
    for element in GN22_ELEMENTS:
        for i, line in enumerate(lines):
            if line.strip().lower() == element:
                # The next lines contain: severity, extent, and comment
                severity = lines[i + 1].strip() if i + 1 < len(lines) else ""
                extent = lines[i + 2].strip() if i + 2 < len(lines) else ""

                # Comment runs until the next known element or section boundary
                comment = _extract_element_comment(lines, i + 3)

                parsed[f"{element} - Severity"] = severity
                parsed[f"{element} - Extent"] = extent
                parsed[f"{element} - Comment"] = comment
                break

    # Step 4: Extract the Comments section at the end of the text
    comments = _extract_comments_section(raw_text)
    if comments:
        parsed["Comments"] = comments

    return parsed


def _extract_element_comment(lines: list[str], start_index: int) -> str:
    """Extract the comment text for a GN22 element.

    Reads lines starting from start_index until it hits another known
    element name, a section header, or an empty/unrelated line.

    Args:
        lines: The full list of text lines.
        start_index: The index to start reading the comment from.

    Returns:
        The comment text, or empty string if none found.
    """

    # Define boundaries that signal the end of a comment
    stop_words = set(GN22_ELEMENTS) | {
        "Column Information", "Test date", "Element Description (GN22)",
        "Severity", "Extent", "Comment", "Comments",
    }

    comment_parts = []
    for i in range(start_index, len(lines)):
        stripped = lines[i].strip()

        # Stop if we hit a known boundary
        if stripped.lower() in {s.lower() for s in stop_words}:
            break

        # Stop if the line looks like a single letter grade (next element's severity)
        if len(stripped) <= 2 and stripped.isalpha() and stripped.isupper():
            break

        if stripped:
            comment_parts.append(stripped)

    return " ".join(comment_parts)


def _extract_comments_section(raw_text: str) -> str:
    """Extract the general Comments section from the end of the text.

    Looks for lines starting with '- ' that appear after the GN22
    element assessments, which represent inspector notes.

    Args:
        raw_text: The full raw text from page 1.

    Returns:
        The combined comments text, or empty string if none found.
    """

    # Find comment lines that start with a dash (inspector notes)
    comment_lines = []
    for line in raw_text.split("\n"):
        stripped = line.strip()
        if stripped.startswith("- "):
            comment_lines.append(stripped)

    return " | ".join(comment_lines)


def build_column_headers() -> list[str]:
    """Build the complete list of column headers for the Excel spreadsheet.

    Combines the standard fields with GN22 element columns
    (Severity, Extent, Comment for each element) and the Comments column.

    Returns:
        An ordered list of column header strings.
    """

    headers = list(COLUMN_ORDER)

    # Add GN22 element columns: 3 columns per element (Severity, Extent, Comment)
    for element in GN22_ELEMENTS:
        headers.append(f"{element} - Severity")
        headers.append(f"{element} - Extent")
        headers.append(f"{element} - Comment")

    # Add the general Comments column at the end
    headers.append("Comments")

    return headers


def load_and_parse_json(json_path: Path) -> list[dict]:
    """Load the output.json file and parse each asset's text into structured data.

    Reads the JSON file, extracts page 1 text for each PDF entry,
    and parses it into a list of structured asset dictionaries.

    Args:
        json_path: Path to the output.json file.

    Returns:
        A list of dictionaries, one per asset, containing all parsed fields.
    """

    # Read the JSON file
    with open(json_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    print(f"Loaded {len(data)} assets from: {json_path}")

    # Parse each asset's page 1 text into structured fields
    parsed_assets = []
    for filename, asset_data in data.items():
        # Get the text from page 1 (where all the data lives)
        pages = asset_data.get("pages", [])
        page_1_text = pages[0]["text"] if pages else ""

        if not page_1_text:
            print(f"  WARNING: No text found on page 1 of {filename}")
            continue

        # Parse the raw text into structured fields
        parsed = parse_asset_text(page_1_text)
        parsed["_source_file"] = filename
        parsed_assets.append(parsed)

        print(f"  Parsed: {parsed.get('Central asset Id', 'unknown')} - {parsed.get('Column Name', 'unknown')}")

    return parsed_assets


def create_excel_report(assets: list[dict], output_path: Path) -> None:
    """Create a formatted Excel spreadsheet from the parsed asset data.

    Generates a workbook with styled headers, one row per asset,
    and auto-fitted column widths for readability.

    Args:
        assets: A list of parsed asset dictionaries.
        output_path: Path where the Excel file will be saved.
    """

    # Create a new workbook and select the active worksheet
    workbook = Workbook()
    worksheet = workbook.active
    worksheet.title = "Asset Report"

    # Build the column headers
    headers = build_column_headers()

    # Step 1: Define header styles (bold white text on dark blue background)
    header_font = Font(name="Calibri", bold=True, color="FFFFFF", size=11)
    header_fill = PatternFill(start_color="2F5496", end_color="2F5496", fill_type="solid")
    header_alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)

    # Step 2: Write the header row with styling
    for col_index, header in enumerate(headers, start=1):
        cell = worksheet.cell(row=1, column=col_index, value=header)
        cell.font = header_font
        cell.fill = header_fill
        cell.alignment = header_alignment

    # Step 3: Sort assets by Central asset Id for consistent ordering
    sorted_assets = sorted(assets, key=lambda a: a.get("Central asset Id", ""))

    # Step 4: Write one data row per asset
    data_alignment = Alignment(vertical="top", wrap_text=True)
    for row_index, asset in enumerate(sorted_assets, start=2):
        for col_index, header in enumerate(headers, start=1):
            value = asset.get(header, "")
            cell = worksheet.cell(row=row_index, column=col_index, value=value)
            cell.alignment = data_alignment

    # Step 5: Auto-fit column widths based on content
    _auto_fit_columns(worksheet, headers)

    # Step 6: Freeze the header row so it stays visible when scrolling
    worksheet.freeze_panes = "A2"

    # Step 7: Build the Critical Assets tab
    critical_assets = _identify_critical_assets(sorted_assets)
    if critical_assets:
        _create_critical_tab(workbook, critical_assets, headers)

    # Step 8: Save the workbook to disk
    workbook.save(output_path)
    print(f"\nExcel report saved to: {output_path}")
    print(f"  Rows: {len(sorted_assets)} assets")
    print(f"  Columns: {len(headers)}")
    print(f"  Critical assets: {len(critical_assets)}")


def _identify_critical_assets(assets: list[dict]) -> list[dict]:
    """Identify assets with % Loss Max >= 30%, indicating Amber or lower structure.

    These columns require examination and replacement.

    Args:
        assets: The full list of parsed asset dictionaries.

    Returns:
        A list of critical asset dicts sorted by % Loss Max descending.
    """

    critical = []
    for asset in assets:
        loss_max_raw = asset.get("% Loss Max", "").strip().replace("%", "").strip()
        if not loss_max_raw:
            continue
        try:
            loss_max = float(loss_max_raw)
        except ValueError:
            continue
        if loss_max >= 30:
            flagged = dict(asset)
            flagged["% Loss Max (value)"] = loss_max
            critical.append(flagged)

    critical.sort(key=lambda a: a["% Loss Max (value)"], reverse=True)
    return critical


def _create_critical_tab(workbook: Workbook, critical_assets: list[dict], base_headers: list[str]) -> None:
    """Create a 'Critical Assets' tab with flagged assets sorted by severity.

    Args:
        workbook: The openpyxl Workbook to add the tab to.
        critical_assets: List of flagged asset dicts with "Flags" field.
        base_headers: The standard column headers from the main report.
    """

    ws = workbook.create_sheet("Critical Assets - Replace")

    headers = list(base_headers)

    header_font = Font(name="Calibri", bold=True, color="FFFFFF", size=11)
    header_fill = PatternFill(start_color="C00000", end_color="C00000", fill_type="solid")
    header_alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)

    for col_index, header in enumerate(headers, start=1):
        cell = ws.cell(row=1, column=col_index, value=header)
        cell.font = header_font
        cell.fill = header_fill
        cell.alignment = header_alignment

    data_alignment = Alignment(vertical="top", wrap_text=True)
    for row_index, asset in enumerate(critical_assets, start=2):
        for col_index, header in enumerate(headers, start=1):
            value = asset.get(header, "")
            cell = ws.cell(row=row_index, column=col_index, value=value)
            cell.alignment = data_alignment

    _auto_fit_columns(ws, headers)
    ws.freeze_panes = "A2"

    print(f"\n  Critical Assets tab: {len(critical_assets)} columns require replacement (% Loss Max >= 30%)")


def _auto_fit_columns(worksheet, headers: list[str]) -> None:
    """Adjust column widths based on the longest value in each column.

    Scans every cell in each column to find the maximum content length,
    then sets the column width with a small padding.

    Args:
        worksheet: The openpyxl worksheet to adjust.
        headers: The list of column headers (used for minimum width).
    """

    for col_index, header in enumerate(headers, start=1):
        # Start with the header length as the minimum width
        max_length = len(header)

        # Check all data rows for longer content
        column_letter = get_column_letter(col_index)
        for cell in worksheet[column_letter]:
            if cell.value:
                max_length = max(max_length, len(str(cell.value)))

        # Set the width with padding, capped at 50 characters to prevent overly wide columns
        worksheet.column_dimensions[column_letter].width = min(max_length + 3, 50)


def main() -> None:
    """Main entry point for the JSON to Excel conversion script."""

    # Step 1: Define file paths relative to the script location
    script_dir = Path(__file__).parent
    json_path = script_dir / "output.json"
    excel_path = script_dir / "asset_report.xlsx"

    # Step 2: Verify the input JSON file exists
    if not json_path.exists():
        print(f"ERROR: Input file not found: {json_path}")
        print("Please run pdf_to_json.py first to generate output.json")
        return

    # Step 3: Load and parse the JSON data into structured asset records
    print("=" * 60)
    print("JSON to Excel Converter")
    print("=" * 60)
    assets = load_and_parse_json(json_path)

    if not assets:
        print("No assets to process. Exiting.")
        return

    # Step 4: Create the formatted Excel spreadsheet
    create_excel_report(assets, excel_path)

    print("=" * 60)
    print("Done!")


if __name__ == "__main__":
    main()
